# Generated by Django 2.2 on 2020-02-28 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20200228_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 0, 6, 45, 463881), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 0, 6, 45, 463881), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 0, 6, 45, 463881), verbose_name='添加时间'),
        ),
    ]
